openapi: 3.0.3
info:
  title: Docusaurus RAG Indexing API
  description: API for extracting content from Docusaurus books, generating embeddings, and managing vector storage
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/v1/index-book:
    post:
      summary: Index a Docusaurus book
      description: Initiates the process of crawling a Docusaurus book, extracting content, generating embeddings, and storing in vector database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexBookRequest'
      responses:
        '202':
          description: Indexing process initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexBookResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/books/{bookId}:
    get:
      summary: Get book details
      description: Retrieve information about a specific indexed book
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the book
      responses:
        '200':
          description: Book details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocusaurusBook'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a book and its indexed content
      description: Removes a book and all associated indexed content from the vector database
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the book
      responses:
        '200':
          description: Book and indexed content deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteBookResponse'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/search:
    post:
      summary: Search indexed content
      description: Performs semantic search on indexed Docusaurus book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        '200':
          description: Search results retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          description: Invalid search parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/books:
    get:
      summary: List all indexed books
      description: Retrieve a list of all indexed Docusaurus books
      responses:
        '200':
          description: List of books retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocusaurusBook'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    IndexBookRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          description: Base URL of the Docusaurus book to index
          example: "https://example-docusaurus-book.com"
        collection_name:
          type: string
          description: Name of the Qdrant collection to store embeddings (optional, defaults to 'rag_embedding')
          example: "my_custom_collection"
        chunk_size:
          type: integer
          description: Size of text chunks in characters (optional, defaults to 1000)
          example: 1000
        chunk_overlap:
          type: integer
          description: Overlap between chunks in characters (optional, defaults to 200)
          example: 200
        model_name:
          type: string
          description: Cohere model name to use for embeddings (optional, defaults to 'embed-english-v3.0')
          example: "embed-english-v3.0"

    IndexBookResponse:
      type: object
      required:
        - job_id
        - status
        - message
      properties:
        job_id:
          type: string
          description: Unique identifier for the indexing job
          example: "idx_job_12345"
        status:
          type: string
          enum: [pending, processing, completed, failed]
          description: Current status of the indexing job
        message:
          type: string
          description: Human-readable message about the operation
          example: "Indexing job initiated successfully"

    DocusaurusBook:
      type: object
      required:
        - id
        - url
        - title
        - status
        - created_at
      properties:
        id:
          type: string
          description: Unique identifier for the book
          example: "book_12345"
        url:
          type: string
          format: uri
          description: Base URL of the Docusaurus book
          example: "https://example-docusaurus-book.com"
        title:
          type: string
          description: Title of the book
          example: "My Technical Book"
        description:
          type: string
          description: Description of the book content
          example: "A comprehensive guide to robotics"
        status:
          type: string
          enum: [pending, indexing, indexed, failed]
          description: Current indexing status of the book
        total_pages:
          type: integer
          description: Number of pages indexed
          example: 42
        last_crawled:
          type: string
          format: date-time
          description: Timestamp of last crawl operation
          example: "2023-10-20T10:00:00Z"
        created_at:
          type: string
          format: date-time
          description: Timestamp when book was first registered
          example: "2023-10-20T09:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp of last update
          example: "2023-10-20T10:00:00Z"

    SearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Search query text
          example: "How to implement SLAM in robotics"
        collection_name:
          type: string
          description: Name of the Qdrant collection to search (optional, defaults to 'rag_embedding')
          example: "my_custom_collection"
        top_k:
          type: integer
          description: Number of results to return (optional, defaults to 5)
          minimum: 1
          maximum: 100
          example: 5
        filters:
          type: object
          description: Optional filters to apply to the search
          properties:
            book_ids:
              type: array
              items:
                type: string
              description: Restrict search to specific books
              example: ["book_12345", "book_67890"]

    SearchResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
        query:
          type: string
          description: The original search query
          example: "How to implement SLAM in robotics"
        took_ms:
          type: number
          description: Time taken for the search operation in milliseconds
          example: 125.5

    SearchResult:
      type: object
      required:
        - text
        - url
        - title
        - similarity_score
      properties:
        text:
          type: string
          description: The text content of the result
          example: "SLAM (Simultaneous Localization and Mapping) is a technique used in robotics..."
        url:
          type: string
          format: uri
          description: URL of the source page
          example: "https://example-docusaurus-book.com/docs/slam-introduction"
        title:
          type: string
          description: Title of the source page
          example: "Introduction to SLAM"
        similarity_score:
          type: number
          format: float
          description: Similarity score between query and result (0.0 to 1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.875
        metadata:
          $ref: '#/components/schemas/ResultMetadata'

    ResultMetadata:
      type: object
      properties:
        book_id:
          type: string
          description: ID of the book containing this content
          example: "book_12345"
        page_id:
          type: string
          description: ID of the page containing this content
          example: "page_67890"
        chunk_id:
          type: string
          description: ID of the text chunk
          example: "chunk_11111"
        created_at:
          type: string
          format: date-time
          description: When this content was indexed
          example: "2023-10-20T10:00:00Z"

    DeleteBookResponse:
      type: object
      required:
        - message
        - deleted_count
      properties:
        message:
          type: string
          description: Human-readable message about the operation
          example: "Book and all associated content deleted successfully"
        deleted_count:
          type: integer
          description: Number of indexed records deleted
          example: 150

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "invalid_request"
        message:
          type: string
          description: Human-readable error message
          example: "The provided URL is not valid"
        details:
          type: object
          description: Additional error details (optional)