// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

 module.exports = {
    tutorialSidebar: [
      'intro',
      {
        type: 'category',
        label: 'Tutorial Basics',
        items: [
          'tutorial-basics/create-a-document',
          'tutorial-basics/create-a-page',
          'tutorial-basics/create-a-blog-post',
          'tutorial-basics/markdown-features',
          'tutorial-basics/deploy-your-site',
          'tutorial-basics/congratulations',
        ],
      },
      {
        type: 'category',
        label: 'Tutorial Extras',
        items: [
          'tutorial-extras/manage-docs-versions',
          'tutorial-extras/translate-your-site',
        ],
      },
      {
        type: 'category',
        label: 'VLA Module',
        items: [
          'modules/vla/intro',
          'modules/vla/chapter-1',
          'modules/vla/chapter-2',
          'modules/vla/chapter-3',
          'modules/vla/final-summary',
          'modules/vla/prerequisites',
          'modules/vla/terminology',
          'modules/vla/architecture',
          'modules/vla/conceptual-examples',
          'modules/vla/practical-exercises',
          'modules/vla/troubleshooting-guide'
        ],
      },
    ],
  };
export default sidebars;
